#! /bin/bash

echo "."
scalafmt src/main/scala/pdbp/utils/productUtils.scala
echo "."
scalafmt src/main/scala/pdbp/utils/functionUtils.scala
echo "."
scalafmt src/main/scala/pdbp/utils/sumUtils.scala
echo "."
scalafmt src/main/scala/pdbp/utils/productAndSumUtils.scala
echo "."
scalafmt src/main/scala/pdbp/utils/effectfulUtils.scala
echo "."
scalafmt src/main/scala/pdbp/types/effect/effectType.scala
echo "."
scalafmt src/main/scala/pdbp/types/effect/toConsole/ToConsole.scala
echo "."
scalafmt src/main/scala/pdbp/types/sum/sumType.scala
echo "."
scalafmt src/main/scala/pdbp/types/active/reading/activeReadingTypes.scala
echo "."
scalafmt src/main/scala/pdbp/types/active/reading/writing/activeReadingWithWritingTypes.scala
echo "."
scalafmt src/main/scala/pdbp/types/active/activeTypes.scala
echo "."
scalafmt src/main/scala/pdbp/types/active/free/activeFreeTypes.scala
echo "."
scalafmt src/main/scala/pdbp/types/active/writing/activeWritingTypes.scala
echo "."
scalafmt src/main/scala/pdbp/types/product/productType.scala
echo "."
scalafmt src/main/scala/pdbp/writable/implicits/toConsole/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/writable/Startable.scala
echo "."
scalafmt src/main/scala/pdbp/writable/Appendable.scala
echo "."
scalafmt src/main/scala/pdbp/writable/Writable.scala
echo "."
scalafmt src/main/scala/pdbp/program/reading/Reading.scala
echo "."
scalafmt src/main/scala/pdbp/program/Composition.scala
echo "."
scalafmt src/main/scala/pdbp/program/implicits/active/reading/int/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/implicits/active/reading/int/writing/toConsole/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/implicits/active/reading/ActiveReadingProgram.scala
echo "."
scalafmt src/main/scala/pdbp/program/implicits/active/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/implicits/active/free/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/implicits/active/writing/toConsole/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/Program.scala
echo "."
scalafmt src/main/scala/pdbp/program/meaning/ofActive/active/implicits.scala
echo "."
echo "."
scalafmt src/main/scala/pdbp/program/meaning/ofActiveFree/active/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/meaning/ofActiveIntReading/activeIntReading/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/meaning/ofActiveWritingToConsole/active/implicits.scala
echo "."
scalafmt src/main/scala/pdbp/program/meaning/ofActiveIntReadingWithWritingToConsole/activeIntReading/implicits.scala
echo "."
echo "."
scalafmt src/main/scala/pdbp/program/Applying.scala
echo "."
scalafmt src/main/scala/pdbp/program/Construction.scala
echo "."
scalafmt src/main/scala/pdbp/program/Function.scala
echo "."
scalafmt src/main/scala/pdbp/program/Aggregation.scala
echo "."
scalafmt src/main/scala/pdbp/program/Condition.scala
echo "."
scalafmt src/main/scala/pdbp/program/ProgramWithApplying.scala
echo "."
scalafmt src/main/scala/pdbp/computation/Sequencing.scala
echo "."
scalafmt src/main/scala/pdbp/computation/Computation.scala
echo "."
scalafmt src/main/scala/pdbp/computation/OperatorLifting.scala
echo "."
scalafmt src/main/scala/pdbp/computation/ObjectLifting.scala
echo "."
scalafmt src/main/scala/pdbp/computation/FunctionLifting.scala
echo "."
scalafmt src/main/scala/pdbp/computation/Resulting.scala
echo "."
scalafmt src/main/scala/pdbp/computation/Binding.scala
echo "."
scalafmt src/main/scala/pdbp/computation/Lifting.scala
echo "."
scalafmt src/main/scala/pdbp/examples/mainKleisliPrograms/effectfulReadingAndWriting/MainSumOfSquaresAsComputation.scala
echo "."
scalafmt src/main/scala/pdbp/examples/mainKleisliPrograms/effectfulReadingAndWriting/MainFactorialAsComputation.scala
echo "."
scalafmt src/main/scala/pdbp/examples/mainKleisliPrograms/effectfulReadingAndWriting/MainSumOfSquaresAsExpression.scala
echo "."
scalafmt src/main/scala/pdbp/examples/main/active/effectfulReadingAndWriting/SumOfSquaresAsComputationMain.scala
echo "."
scalafmt src/main/scala/pdbp/examples/main/active/effectfulReadingAndWriting/FactorialAsComputationMain.scala
echo "."
scalafmt src/main/scala/pdbp/examples/utils/functionUtils.scala
echo "."
scalafmt src/main/scala/pdbp/examples/kleisliPrograms/SumOfSquaresAsComputation.scala
echo "."
scalafmt src/main/scala/pdbp/examples/kleisliPrograms/FactorialAsComputation.scala
echo "."
scalafmt src/main/scala/pdbp/examples/objects/active/effectfulReadingAndWriting/mainSumOfSquaresAsComputation.scala
echo "."
scalafmt src/main/scala/pdbp/examples/objects/active/effectfulReadingAndWriting/mainFactorialAsComputation.scala
echo "."
scalafmt src/main/scala/pdbp/natural/transformation/binary/NaturalBinaryTypeConstructorTransformation.scala
echo "."
scalafmt src/main/scala/pdbp/natural/transformation/unary/NaturalUnaryTypeConstructorTransformation.scala
echo "."
scalafmt src/main/scala/demo/FunctionsAndExpressions.scala
echo "."
scalafmt src/main/scala/demo/resulting.scala
echo "."
scalafmt src/main/scala/demo/Variance.scala
echo "."
scalafmt src/main/scala/demo/bindingOperator.scala
echo "."
scalafmt src/main/scala/demo/definingDescriptions.scala
echo "."
scalafmt src/main/scala/examples/programs/FactorialTopDown.scala
echo "."
scalafmt src/main/scala/examples/programs/Factorial.scala
echo "."
scalafmt src/main/scala/examples/programs/FactorialAsFunction.scala
echo "."
scalafmt src/main/scala/examples/main/active/reading/int/effectfulWriting/FactorialMultipliedByIntReadMain.scala
echo "."
scalafmt src/main/scala/examples/main/active/reading/int/effectfulWriting/FactorialOfIntReadMain.scala
echo "."
scalafmt src/main/scala/examples/main/active/writing/toConsole/effectfulReading/FactorialWrittenToConsoleMain.scala
echo "."
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/FactorialOfIntReadWrittenToConsoleMain.scala
echo "."
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/FactorialOfIntReadWritingToConsoleWrittenToConsoleMain.scala
echo "."
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/effectfulWriting/FactorialOfIntReadWrittenToConsoleMain.scala
echo "."
scalafmt src/main/scala/examples/main/active/effectfulReadingAndWriting/FactorialMain.scala
echo "."
scalafmt src/main/scala/examples/main/Main.scala
echo "."
scalafmt src/main/scala/examples/utils/effects/implicits.scala
echo "."
scalafmt src/main/scala/examples/utils/functionUtils.scala
echo "."
scalafmt src/main/scala/examples/objects/active/reading/int/effectfulWriting/mainFactorialMultipliedByIntRead.scala
echo "."
scalafmt src/main/scala/examples/objects/active/reading/int/effectfulWriting/mainFactorialOfIntRead.scala
echo "."
scalafmt src/main/scala/examples/objects/active/writing/toConsole/effectfulReading/mainFactorialWrittenToConsole.scala
echo "."
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/effectfulWriting/mainFactorialOfIntReadWritingToConsole.scala
echo "."
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/mainFactorialOfIntReadWrittenToConsole.scala
echo "."
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/mainFactorialOfIntReadWritingToConsoleWrittenToConsole.scala
echo "."
scalafmt src/main/scala/examples/objects/active/effectfulReadingAndWriting/mainFactorial.scala
echo "."
scalafmt src/main/scala/examples/objects/active/free/effectfulReadingAndWriting/mainFactorial.scala
echo "."
scalafmt src/main/scala/examples/mainPrograms/effectfulReadingAndWriting/MainFactorial.scala
echo "."
scalafmt src/main/scala/examples/mainPrograms/effectfulReadingAndWriting/MainFactorialTopDown.scala
echo "."
scalafmt src/main/scala/examples/mainPrograms/effectfulReadingAndWriting/MainFactorialAsFunction.scala


