#! /bin/bash

scalafmt src/main/scala/pdbp/utils/productUtils.scala
scalafmt src/main/scala/pdbp/utils/functionUtils.scala
scalafmt src/main/scala/pdbp/utils/sumUtils.scala
scalafmt src/main/scala/pdbp/utils/productAndSumUtils.scala
scalafmt src/main/scala/pdbp/utils/effectfulUtils.scala
scalafmt src/main/scala/pdbp/types/effect/effectType.scala
scalafmt src/main/scala/pdbp/types/effect/toConsole/ToConsole.scala
scalafmt src/main/scala/pdbp/types/sum/sumType.scala
scalafmt src/main/scala/pdbp/types/active/reading/activeReadingTypes.scala
scalafmt src/main/scala/pdbp/types/active/reading/writing/activeReadingWithWritingTypes.scala
scalafmt src/main/scala/pdbp/types/active/activeTypes.scala
scalafmt src/main/scala/pdbp/types/active/free/activeFreeTypes.scala
scalafmt src/main/scala/pdbp/types/active/writing/activeWritingTypes.scala
scalafmt src/main/scala/pdbp/types/product/productType.scala
scalafmt src/main/scala/pdbp/writable/implicits/toConsole/implicits.scala
scalafmt src/main/scala/pdbp/writable/Startable.scala
scalafmt src/main/scala/pdbp/writable/Appendable.scala
scalafmt src/main/scala/pdbp/writable/Writable.scala
scalafmt src/main/scala/pdbp/program/reading/Reading.scala
scalafmt src/main/scala/pdbp/program/Composition.scala
scalafmt src/main/scala/pdbp/program/implicits/active/reading/int/implicits.scala
scalafmt src/main/scala/pdbp/program/implicits/active/reading/int/writing/toConsole/implicits.scala
scalafmt src/main/scala/pdbp/program/implicits/active/reading/ActiveReadingProgram.scala
scalafmt src/main/scala/pdbp/program/implicits/active/implicits.scala
scalafmt src/main/scala/pdbp/program/implicits/active/free/implicits.scala
scalafmt src/main/scala/pdbp/program/implicits/active/writing/toConsole/implicits.scala
scalafmt src/main/scala/pdbp/program/Program.scala
scalafmt src/main/scala/pdbp/program/meaning/ofActive/active/implicits.scala
scalafmt src/main/scala/pdbp/program/meaning/ofActiveFree/active/implicits.scala
scalafmt src/main/scala/pdbp/program/meaning/ofActiveIntReading/activeIntReading/implicits.scala
scalafmt src/main/scala/pdbp/program/Applying.scala
scalafmt src/main/scala/pdbp/program/Construction.scala
scalafmt src/main/scala/pdbp/program/Function.scala
scalafmt src/main/scala/pdbp/program/Aggregation.scala
scalafmt src/main/scala/pdbp/program/Condition.scala
scalafmt src/main/scala/pdbp/program/ProgramWithApplying.scala
scalafmt src/main/scala/pdbp/computation/Sequencing.scala
scalafmt src/main/scala/pdbp/computation/Computation.scala
scalafmt src/main/scala/pdbp/computation/OperatorLifting.scala
scalafmt src/main/scala/pdbp/computation/ObjectLifting.scala
scalafmt src/main/scala/pdbp/computation/FunctionLifting.scala
scalafmt src/main/scala/pdbp/computation/Resulting.scala
scalafmt src/main/scala/pdbp/computation/Binding.scala
scalafmt src/main/scala/pdbp/computation/Lifting.scala
scalafmt src/main/scala/pdbp/examples/mainKleisliPrograms/effectfulReadingAndWriting/MainSumOfSquaresAsComputation.scala
scalafmt src/main/scala/pdbp/examples/mainKleisliPrograms/effectfulReadingAndWriting/MainSumOfSquaresAsExpression.scala
scalafmt src/main/scala/pdbp/examples/main/active/effectfulReadingAndWriting/SumOfSquaresAsComputationMain.scala
scalafmt src/main/scala/pdbp/examples/utils/functionUtils.scala
scalafmt src/main/scala/pdbp/examples/kleisliPrograms/SumOfSquaresAsComputation.scala
scalafmt src/main/scala/pdbp/examples/objects/active/effectfulReadingAndWriting/mainSumOfSquaresAsComputation.scala
scalafmt src/main/scala/pdbp/natural/transformation/binary/NaturalBinaryTypeConstructorTransformation.scala
scalafmt src/main/scala/pdbp/natural/transformation/unary/NaturalUnaryTypeConstructorTransformation.scala
scalafmt src/main/scala/demo/FunctionsAndExpressions.scala
scalafmt src/main/scala/demo/resulting.scala
scalafmt src/main/scala/demo/Variance.scala
scalafmt src/main/scala/demo/bindingOperator.scala
scalafmt src/main/scala/demo/LanguageLevelMeaning.scala
scalafmt src/main/scala/examples/programs/FactorialTopDown.scala
scalafmt src/main/scala/examples/programs/Factorial.scala
scalafmt src/main/scala/examples/programs/FactorialAsFunction.scala
scalafmt src/main/scala/examples/programs/writing/PointfreeWritingAtomicPrograms.scala
scalafmt src/main/scala/examples/main/meaning/ofActiveFree/active/effectfulReadingAndWriting/FactorialMain.scala
scalafmt src/main/scala/examples/main/meaning/ofActiveIntReading/activeIntReading/effectfulWriting/FactorialOfIntReadMain.scala
scalafmt src/main/scala/examples/main/active/reading/int/effectfulWriting/FactorialMultipliedByIntReadMain.scala
scalafmt src/main/scala/examples/main/active/reading/int/effectfulWriting/FactorialOfIntReadMain.scala
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/FactorialOfIntReadWrittenToConsoleMain.scala
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/FactorialOfIntReadWritingToConsoleWrittenToConsoleMain.scala
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/effectfulWriting/FactorialOfIntReadPointfreeWritingToConsoleMain.scala
scalafmt src/main/scala/examples/main/active/reading/int/writing/toConsole/effectfulWriting/FactorialOfIntReadWritingToConsoleMain.scala
scalafmt src/main/scala/examples/main/active/effectfulReadingAndWriting/FactorialMain.scala
scalafmt src/main/scala/examples/main/Main.scala
scalafmt src/main/scala/examples/utils/effects/implicits.scala
scalafmt src/main/scala/examples/utils/functionUtils.scala
scalafmt src/main/scala/examples/utils/EffectfulUtils.scala
scalafmt src/main/scala/examples/objects/active/reading/int/effectfulWriting/mainFactorialMultipliedByIntRead.scala
scalafmt src/main/scala/examples/objects/active/reading/int/effectfulWriting/mainFactorialOfIntRead.scala
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/effectfulWriting/mainFactorialOfIntReadPointfreeWritingToConsole.scala
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/effectfulWriting/mainFactorialOfIntReadWritingToConsole.scala
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/mainFactorialOfIntReadWrittenToConsole.scala
scalafmt src/main/scala/examples/objects/active/reading/int/writing/toConsole/mainFactorialOfIntReadWritingToConsoleWrittenToConsole.scala
scalafmt src/main/scala/examples/objects/active/effectfulReadingAndWriting/mainFactorial.scala
scalafmt src/main/scala/examples/objects/active/free/effectfulReadingAndWriting/mainFactorial.scala
scalafmt src/main/scala/examples/programs/writing/PointfreeWritingFactorial.scala
scalafmt src/main/scala/examples/main/meaning/ofActive/active/effectfulReadingAndWriting/FactorialMain.scala
scalafmt src/main/scala/examples/mainPrograms/reading/int/effectfulWriting/MainFactorialOfIntRead.scala
scalafmt src/main/scala/examples/mainPrograms/effectfulReadingAndWriting/MainFactorial..scala
scalafmt src/main/scala/examples/mainPrograms/effectfulReadingAndWriting/MainFactorialTopDown.scala
scalafmt src/main/scala/examples/mainPrograms/effectfulReadingAndWriting/MainFactorialAsFunction.scala


